### ISSUE TITLE
No push sent to Android devices

### ISSUE THREAD

**Issue by dgurney75** [Pushwoosh/pushwoosh-adobe-air#29]
I've integrated the new Pushwoosh ANE for Android 12 devices, and I am getting the token now, but can't seem to get the push notification to the device. The device is set up as a test device and when i send a test woosh, nothing is received.

I did see this in the logs:

2022-09-13 11:07:09.876 15826-15826/air.com.maritz.lexusEnCompass E/AndroidRuntime: FATAL EXCEPTION: main
    Process: air.com.maritz.lexusEnCompass, PID: 15826
    java.lang.RuntimeException: Unable to instantiate receiver com.google.firebase.iid.FirebaseInstanceIdReceiver: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.iid.FirebaseInstanceIdReceiver" on path: DexPathList[[zip file "/data/app/~~maW_EGKhnngLca5JDno-Sg==/air.com.maritz.lexusEnCompass-EASsB4zW063C3Jc2kQrQEA==/base.apk"],nativeLibraryDirectories=[/data/app/~~maW_EGKhnngLca5JDno-Sg==/air.com.maritz.lexusEnCompass-EASsB4zW063C3Jc2kQrQEA==/lib/arm64, /data/app/~~maW_EGKhnngLca5JDno-Sg==/air.com.maritz.lexusEnCompass-EASsB4zW063C3Jc2kQrQEA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:4294)
        at android.app.ActivityThread.access$1600(ActivityThread.java:247)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2064)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.iid.FirebaseInstanceIdReceiver" on path: DexPathList[[zip file "/data/app/~~maW_EGKhnngLca5JDno-Sg==/air.com.maritz.lexusEnCompass-EASsB4zW063C3Jc2kQrQEA==/base.apk"],nativeLibraryDirectories=[/data/app/~~maW_EGKhnngLca5JDno-Sg==/air.com.maritz.lexusEnCompass-EASsB4zW063C3Jc2kQrQEA==/lib/arm64, /data/app/~~maW_EGKhnngLca5JDno-Sg==/air.com.maritz.lexusEnCompass-EASsB4zW063C3Jc2kQrQEA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateReceiver(AppComponentFactory.java:110)
        at androidx.core.app.CoreComponentFactory.instantiateReceiver(CoreComponentFactory.java:60)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:4287)
        at android.app.ActivityThread.access$1600(ActivityThread.java:247) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2064) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7839) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by wfhm** [comment]
@dgurney75 hi,

Resolving this issue will require accessing to some sensitive data, such as push tokens, app IDs etc, so I would suggest creating a support ticket at https://help.pushwoosh.com/hc/en-us/requests/new, providing app ID and problematic push token and mentioning this issue in it, so we could easily track it.

**Comment by dgurney75** [comment]
I sent a message to the support team and they said that the error log showed that it was not related to PushWoosh SDK. Not sure what to do, since it was all working before Android 12 release.

It has something to do with Firebase
Unable to instantiate receiver com.google.firebase.iid.FirebaseInstanceIdReceive

The lines in the manifest that affect it is this.

<receiver 
         android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver"
         android:exported="true"
         android:permission="com.google.android.c2dm.permission.SEND">
          <intent-filter>
            <action android:name="com.google.android.c2dm.intent.RECEIVE"/>
            <category android:name="air.com.maritz.lexusEnCompass"/>
          </intent-filter>
        </receiver>


Maybe Michael would know.

**Comment by dgurney75** [comment]
UPDATE: figured it out. The latest com.google.firebase.core does not work with Pushwoosh. I reverted back to the last release that was included in the sample project folder and it works now.

**Comment by wfhm** [comment]
@dgurney75 Fixed with the latest release.
